name: SVV Pipeline

on:
  push:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Repository Structure
        run: |
          echo "Checking folders..."
          ls
